/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class game_wq_sohook_SoHookCore */

#ifndef _Included_game_wq_sohook_SoHookCore
#define _Included_game_wq_sohook_SoHookCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     game_wq_sohook_SoHookCore
 * Method:    hookJNIString
 * Signature: ()Ljava/lang/String;
 */


#ifdef __cplusplus
}
#endif
#endif
